added thermostat class
opravdin/weback-unofficial pull request #14
Opened 2021-02-23 16:41 UTC by matthiaslexer

Hi there! 

This is my first pull request, so please be kind. :smile: 
At first thanks for your work, you've helped me to finally control my thermostat via an API. 
I've tested this with two of my flourleon thermostats and it works great.

2021-02-23 17:22 UTC, opravdin requested changes
I had add some comments in your code. Really appreciate the work you done btw.

2021-02-23 17:22 UTC, opravdin commented on weback_unofficial/thermostat.py
> +TEMP_MULTIPLIER = 2
You need to describe this constant in comments (what is meant for and why it's 2)

2021-02-23 17:22 UTC, opravdin commented on weback_unofficial/thermostat.py
> +        return self.shadow.get('air_tem') / 10
Please, move this 10 value to constants section and add description for it

2021-02-23 17:22 UTC, opravdin commented on weback_unofficial/thermostat.py
> +        print(mode)
Remove this print from production version of library please

2021-02-23 17:22 UTC, opravdin commented on weback_unofficial/thermostat.py
> +    def format_auto_settings(self, day):
It's better to describe input and output of this function, hard to guess from code

2021-02-23 17:22 UTC, opravdin commented on weback_unofficial/thermostat.py
> +    def autosettings(self):
It's better to move these dow values in constants section, but it's not necessary at this point. I can do it by myself in future versions.

2021-02-23 18:28 UTC, opravdin commented
Cool, thank you for updating your code. I will update this in pypi this week. Could you provide some code examples for me to include in documentation and your thermostat model to include in verified devices list?

2021-02-23 18:29 UTC, opravdin approved these changes
Everything looks fine now, thanks

2021-02-23 18:29 UTC, merged

2021-02-23 18:30 UTC, matthiaslexer commented
thanks for the suggestions, fixed all of them. 
It's a Floureon Thermostat (https://www.aliexpress.com/i/32799368790.html). 

If you want to, I can also send you a copy of the shadow and description response.

2021-02-23 18:32 UTC, opravdin commented
> If you want to, I can also send you a copy of the shadow and description response.

Yes, that would be perfect! I have plans to add this module to home assistant weback integration, so it will be nice to have this kind of cheatsheet on hands

2021-02-23 18:36 UTC, matthiaslexer commented
> > If you want to, I can also send you a copy of the shadow and description response.
> 
> Yes, that would be perfect! I have plans to add this module to home assistant weback integration, so it will be nice to have this kind of cheatsheet on hands

Will send it to you tomorrow. These were also my plans (I only did it for the home assistant integration), so I guess you will get another pull request from me this week.

2021-02-24 06:59 UTC, matthiaslexer commented
This is my own documentation, hope you can work with it. 

# Floureon Thermostat Weback Integration

##  Device List
The device list call returns all my thermostats, which are visible in the app.

```json
[
    {
        "Thing_Name": "by-t03-mac-address",
        "Thing_Nick_Name": "Wohnzimmer",
        "Image_Url": "https://app.grit-tech.cn/deviceImage/by/t03/by-t03.png",
        "Sub_type": "by-t03"
    },
    {
        "Thing_Name": "by-t03-mac-address",
        "Thing_Nick_Name": "Gang",
        "Image_Url": "https://app.grit-tech.cn/deviceImage/by/t03/by-t03.png",
        "Sub_type": "by-t03"
    }
]
```
##  Description
The description i've got from aws contains just personal details (e.g. ip adress, location,...) and the following values which seem to be unique for that type of device

```json
{
    "thingTypeName": "_THERMOSTAT",
    "attributes": {
        ...
        "app_name": "WeBack",
        "sub_type": "by-t03",
        ...
    }
}    
```
##  Shadow Object
The shadow object contains all the properties which are also configurable through the app. 
I can describle the following ones: 

**workmode** 
"hand" | "auto"

hand just heats till the set_tem is reached, auto heats accordings to the actions for each day (you can set them up through the app). These actions are saved into Mon, Tues,... (maximum and minimum amount is 6), if you don't set any actions it will just create 6 for you which has the min temperatue (= does nothing)

**tem_uint**
the unit of the temperature (i've got celsius, i guess fahrenheit is also a possible value)

**set_tem** 
the goal temperature of the sensor, it goes from 12 (6 degrees) to 69 (34.5 degrees). Must be a full inte

**air_tem**
the current temperature (also visible on the thermostat), you need to divide it through 10 to get a normal temperature value (211 means 21.1 degrees). 

**safe_lock**
if on you can't change the status of the thermostat on the device itself (a kind of child lock)

**bgl**
controls the background light

**freeze_protect**
automatically turns on heating while below 5 degrees

**controle_mode** 
i've got inter, which menas it uses the internal probe, the app also tells us there is an outer mode (external probe temperature control) and a double mode (two probes simultaneously controlled)

```json
{
    "connected": "true",
    "config_app": "WeBack",
    "firmware_version": "3.2.0rel",
    "offset_hours": 1,
    "offset_minutes": 0,
    "working_status": "on",
    "workmode": "hand",
    "air_tem": 211,
    "floor_tem": 0,
    "set_tem": 70,
    "safe_lock": "on",
    "bgl": "on",
    "poweron_state": "keep",
    "freeze_protect": "off",
    "tem_uint": "C",
    "control_mode": "inter",
    "tem_cal": -20,
    "inter_sen_cal": 10,
    "outer_sen_cal": 30,
    "outer_sen_top": 55,
    "Mon": "04:50_043C,08:00_030C,17:00_043C,20:00_030C,20:00_030C,20:00_030C",
    "Tues": "04:50_043C,08:00_030C,17:00_043C,20:00_030C,20:00_030C,20:00_030C",
    "Wed": "04:50_043C,08:00_030C,17:00_043C,20:00_030C,20:00_030C,20:00_030C",
    "Thur": "04:50_043C,08:00_030C,17:00_043C,20:00_030C,20:00_030C,20:00_030C",
    "Fri": "04:50_043C,08:00_030C,17:00_043C,20:00_030C,20:00_030C,20:00_030C",
    "Sat": "07:20_043C,10:30_030C,17:00_043C,20:00_030C,20:00_030C,20:00_030C",
    "Sun": "07:20_043C,10:30_030C,17:00_043C,20:00_030C,20:00_030C,20:00_030C"
}
```

## Playground Code
```python
from weback_unofficial.client import WebackApi
from weback_unofficial.thermostat import Thermostat, AUTO

client = WebackApi(username, password)
session = client.get_session() # Returns Amazon Session from boto3 package 
devices = client.device_list()
device_name = devices[0]['Thing_Name']

thermostat = Thermostat(device_name, client)
thermostat.update()

# set auto mode (thermoter uses actions which are configured)
thermostat.setMode(AUTO)

# set manual temperature (also sets mode to MANUAL)
thermostat.setTemp(25)

# check if thermostat is currently heating
print(thermostat.is_heating)

# get current temperature
print(thermostat.temperature)
```

2021-03-09 08:04 UTC, matthiaslexer commented
@opravdin could you please release a new version on PyPI? Would need it for the home assistant integration.

2021-03-09 08:07 UTC, opravdin commented
> @opravdin could you please release a new version on PyPI? Would need it for the home assistant integration.

Yes, sure. I was busy coding the robot vacuum [clean map](https://community.home-assistant.io/t/weback-cloud-integration-testers-and-help-required/186155/67). I will do it today.